### PR TITLE
Add media_player.linkplay integration

### PR DESCRIPTION
**Pull request by Limych**

### CODE REVIEW

**Comment by ludeeus** [comment]
@hacsbot You sleeping?

**Comment by ludeeus** [comment]
I guess so...

**Comment by ludeeus** [comment]
IT'S ALIVE!!! 🎉

**Comment by ukscarface** [comment]
Hello, i cannot get this to work with my home assistant setup 

copied the three files to the custom_components-linkplay folder but when i go to reboot i have a error log of the manifest file causing failure? any ideas or help please?

**Pull request merged**
