### PR TITLE
add eifinger/open_route_service

### PR DESCRIPTION
**Pull request by eifinger**

### CODE REVIEW

**Comment by ludeeus** [comment]
You can disregard the missing hacs.json.
But this needs a rebase + the json is not valid.

**Comment by eifinger** [comment]
You are right the `config_flow` should be removed. Something else?

**Comment by ludeeus** [comment]
Just a rebase, and fixig the json format in the file you are changing here, hint it's missing a `,`

**Comment by eifinger** [comment]
I was *so* sure I added that `,` 😱

**Pull request merged**
