### PR TITLE
Added beerbolaget to default repositories.

### PR DESCRIPTION
**Pull request by Ceerbeerus**

### CODE REVIEW

**Comment by ludeeus** [comment]
@Ceerbeerus Can you add a PR with the same change against `next` (rebasing now is a PITA)

**Comment by ludeeus** [comment]
<https://github.com/custom-components/hacs/commit/be71aa5861f549e8f072be53ef3ddd66c862a0ac>
I manually added it to the correct branch

**Comment by ludeeus** [comment]
@Ceerbeerus You need to restructure your repository before I release 0.10.0 (saturday CET)
<https://custom-components.github.io/hacs/developer/integration/>
_If not I would have to remove it._

**Comment by Ceerbeerus** [comment]
Yea, I’ll take care of it asap.

**Pull request closed without merging**
