### PR TITLE
Update wrong link in const.py

### PR DESCRIPTION
**Pull request by mgiako**
Just a - instead of _

### CODE REVIEW

**Comment by ludeeus** [comment]
Looks like I need to do a cleanup, this is not even used 🙈 , but thanks :)

**Comment by mgiako** [comment]
I think it's used in the log. or not? In the log the issue link is wrong...

**Comment by mgiako** [comment]
-------------------------------------------------------------------
HACS (Home Assistant Community Store)
Version: 0.2.1
This is a custom component
If you have any issues with this you need to open an issue here:
https://github.com/custom_components/hacs/issues
-------------------------------------------------------------------
this is the log, and it's where i found the wrong link

**Comment by ludeeus** [comment]
Ahhhh, yeah
It's used for `ISSUE_URL` 👍

**Comment by ludeeus** [comment]
I still need to do a cleanup :P

**Pull request merged**
