### PR TITLE
Add midnight theme to HACS

### PR DESCRIPTION
**Pull request by pho3nixf1re**
I have created a repo for managing the midnight theme. Background can be found in [this thread](https://community.home-assistant.io/t/midnight-theme/28598) from the community forums.

Closes https://github.com/pho3nixf1re/home-assistant-theme-midnight/issues/1 .

### CODE REVIEW

**Comment by pho3nixf1re** [comment]
Wait to merge this. The repo may be moving. I'll update this PR pending the outcome of that.

**Comment by ludeeus** [comment]
What's the difference between this, and https://github.com/home-assistant-community-themes/midnight?

**Comment by pho3nixf1re** [comment]
That is the new community theme repo. I need to be sure it is fully updated with the fixes in mine then that repo should replace mine.

**Comment by ludeeus** [comment]
Since that all themes in that org already are in HACS, I think we can close this PR?

**Comment by pho3nixf1re** [comment]
sure

**Pull request closed without merging**
