### PR TITLE
Improved Polish translation

### PR DESCRIPTION
**Pull request by Wishnia**

### CODE REVIEW

**Comment by ludeeus** [comment]
@bieniu could you have a look at this, my polish knowledge is non-existing :P

**Comment by bieniu** [comment]
Translation for strings config->user->data->appdaemon, python_script, theme and error->auth are OK. But the other translations are too literal and in my opinion mine are better 😉

**Comment by ludeeus** [comment]
I only have Google Translate to go on, and there nothing made sense 😄 

@Wishnia Can you look at @bieniu's comment?

**Comment by Wishnia** [comment]
@bieniu So, how about combination of our changes? ;)

**Comment by bieniu** [comment]
I think that best solution is close that PR and change some strings on Lokalise.

**Pull request closed without merging**
