### PR TITLE
Add Terminal instructions to step 3

### PR DESCRIPTION
**Pull request by DeadEnded**
Add Terminal instructions to step 3

### CODE REVIEW

**Comment by ludeeus** [comment]
This one is clean  🎉 

But there is still the issue of using the default branch (master) when doing it like this :/

**Comment by ludeeus** [comment]
So a more acceptable flow would be:

```bash
# Navigate to your custom_components directory
cd /config/custom_components # This location is different from installation to installation.

git clone https://github.com/custom-components/hacs.git hacs_temp
cd hacs_temp
git checkout $(git describe --tags `git rev-list --tags --max-count=1`)
cd ../
cp -r hacs_temp/custom_components/hacs hacs
rm -R hacs_temp
```

**Comment by DeadEnded** [comment]
So do you want me to change it to the "next" branch?
Or re-base off the 0.7.0 tag (if that is possible... haven't tried it yet).

**Comment by ludeeus** [comment]
No no, how you made it is fine,
But the content is not :)

**Comment by DeadEnded** [comment]
Ah!
I understand now what you are saying.
There is a better way to copy the data locally and move to the custom components folder.

Since you already posted a more appropriate flow, I will update the pull with this.
I will have to read on the checkout as I don't know it or why to use it.

Thanks,
DeadEnd

**Comment by ludeeus** [comment]
Did some restructure, and moved it to a separate location.
Have a look before I merge it.

**Comment by DeadEnded** [comment]
looks great!

**Pull request merged**
