### PR TITLE
docs: fix typo examlpe

### PR DESCRIPTION
**Pull request by eifinger**

### CODE REVIEW

**Comment by ludeeus** [comment]
Hi, @eifinger 👋

An automatic task is now running some initial checks before this can be merged.
When those are done, someone will manually ensure that that it's OK. 💃

While you wait, you can have a look at [this cute kitten 😺](https://www.youtube.com/watch?v=0Bmhjf0rKe8)


_This message was automatically generated🚀_

**Comment by eifinger** [comment]
Will fix in another PR

**Comment by ludeeus** [comment]
Hi, {'avatar_url': 'https://avatars1.githubusercontent.com/u/1481961?v=4', 'events_url': 'https://api.github.com/users/eifinger/events{/privacy}', 'followers_url': 'https://api.github.com/users/eifinger/followers', 'following_url': 'https://api.github.com/users/eifinger/following{/other_user}', 'gists_url': 'https://api.github.com/users/eifinger/gists{/gist_id}', 'gravatar_id': '', 'html_url': 'https://github.com/eifinger', 'id': 1481961, 'login': 'eifinger', 'node_id': 'MDQ6VXNlcjE0ODE5NjE=', 'organizations_url': 'https://api.github.com/users/eifinger/orgs', 'received_events_url': 'https://api.github.com/users/eifinger/received_events', 'repos_url': 'https://api.github.com/users/eifinger/repos', 'site_admin': False, 'starred_url': 'https://api.github.com/users/eifinger/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/eifinger/subscriptions', 'type': 'User', 'url': 'https://api.github.com/users/eifinger'}

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, {'avatar_url': 'https://avatars2.githubusercontent.com/u/15093472?v=4', 'events_url': 'https://api.github.com/users/ludeeus/events{/privacy}', 'followers_url': 'https://api.github.com/users/ludeeus/followers', 'following_url': 'https://api.github.com/users/ludeeus/following{/other_user}', 'gists_url': 'https://api.github.com/users/ludeeus/gists{/gist_id}', 'gravatar_id': '', 'html_url': 'https://github.com/ludeeus', 'id': 15093472, 'login': 'ludeeus', 'node_id': 'MDQ6VXNlcjE1MDkzNDcy', 'organizations_url': 'https://api.github.com/users/ludeeus/orgs', 'received_events_url': 'https://api.github.com/users/ludeeus/received_events', 'repos_url': 'https://api.github.com/users/ludeeus/repos', 'site_admin': False, 'starred_url': 'https://api.github.com/users/ludeeus/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ludeeus/subscriptions', 'type': 'User', 'url': 'https://api.github.com/users/ludeeus'}

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, {'avatar_url': 'https://avatars2.githubusercontent.com/u/15093472?v=4', 'events_url': 'https://api.github.com/users/ludeeus/events{/privacy}', 'followers_url': 'https://api.github.com/users/ludeeus/followers', 'following_url': 'https://api.github.com/users/ludeeus/following{/other_user}', 'gists_url': 'https://api.github.com/users/ludeeus/gists{/gist_id}', 'gravatar_id': '', 'html_url': 'https://github.com/ludeeus', 'id': 15093472, 'login': 'ludeeus', 'node_id': 'MDQ6VXNlcjE1MDkzNDcy', 'organizations_url': 'https://api.github.com/users/ludeeus/orgs', 'received_events_url': 'https://api.github.com/users/ludeeus/received_events', 'repos_url': 'https://api.github.com/users/ludeeus/repos', 'site_admin': False, 'starred_url': 'https://api.github.com/users/ludeeus/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ludeeus/subscriptions', 'type': 'User', 'url': 'https://api.github.com/users/ludeeus'}

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, {'avatar_url': 'https://avatars2.githubusercontent.com/u/15093472?v=4', 'events_url': 'https://api.github.com/users/ludeeus/events{/privacy}', 'followers_url': 'https://api.github.com/users/ludeeus/followers', 'following_url': 'https://api.github.com/users/ludeeus/following{/other_user}', 'gists_url': 'https://api.github.com/users/ludeeus/gists{/gist_id}', 'gravatar_id': '', 'html_url': 'https://github.com/ludeeus', 'id': 15093472, 'login': 'ludeeus', 'node_id': 'MDQ6VXNlcjE1MDkzNDcy', 'organizations_url': 'https://api.github.com/users/ludeeus/orgs', 'received_events_url': 'https://api.github.com/users/ludeeus/received_events', 'repos_url': 'https://api.github.com/users/ludeeus/repos', 'site_admin': False, 'starred_url': 'https://api.github.com/users/ludeeus/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ludeeus/subscriptions', 'type': 'User', 'url': 'https://api.github.com/users/ludeeus'}

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, {'avatar_url': 'https://avatars2.githubusercontent.com/u/15093472?v=4', 'events_url': 'https://api.github.com/users/ludeeus/events{/privacy}', 'followers_url': 'https://api.github.com/users/ludeeus/followers', 'following_url': 'https://api.github.com/users/ludeeus/following{/other_user}', 'gists_url': 'https://api.github.com/users/ludeeus/gists{/gist_id}', 'gravatar_id': '', 'html_url': 'https://github.com/ludeeus', 'id': 15093472, 'login': 'ludeeus', 'node_id': 'MDQ6VXNlcjE1MDkzNDcy', 'organizations_url': 'https://api.github.com/users/ludeeus/orgs', 'received_events_url': 'https://api.github.com/users/ludeeus/received_events', 'repos_url': 'https://api.github.com/users/ludeeus/repos', 'site_admin': False, 'starred_url': 'https://api.github.com/users/ludeeus/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ludeeus/subscriptions', 'type': 'User', 'url': 'https://api.github.com/users/ludeeus'}

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, {'avatar_url': 'https://avatars2.githubusercontent.com/u/15093472?v=4', 'events_url': 'https://api.github.com/users/ludeeus/events{/privacy}', 'followers_url': 'https://api.github.com/users/ludeeus/followers', 'following_url': 'https://api.github.com/users/ludeeus/following{/other_user}', 'gists_url': 'https://api.github.com/users/ludeeus/gists{/gist_id}', 'gravatar_id': '', 'html_url': 'https://github.com/ludeeus', 'id': 15093472, 'login': 'ludeeus', 'node_id': 'MDQ6VXNlcjE1MDkzNDcy', 'organizations_url': 'https://api.github.com/users/ludeeus/orgs', 'received_events_url': 'https://api.github.com/users/ludeeus/received_events', 'repos_url': 'https://api.github.com/users/ludeeus/repos', 'site_admin': False, 'starred_url': 'https://api.github.com/users/ludeeus/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ludeeus/subscriptions', 'type': 'User', 'url': 'https://api.github.com/users/ludeeus'}

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, {'avatar_url': 'https://avatars2.githubusercontent.com/u/15093472?v=4', 'events_url': 'https://api.github.com/users/ludeeus/events{/privacy}', 'followers_url': 'https://api.github.com/users/ludeeus/followers', 'following_url': 'https://api.github.com/users/ludeeus/following{/other_user}', 'gists_url': 'https://api.github.com/users/ludeeus/gists{/gist_id}', 'gravatar_id': '', 'html_url': 'https://github.com/ludeeus', 'id': 15093472, 'login': 'ludeeus', 'node_id': 'MDQ6VXNlcjE1MDkzNDcy', 'organizations_url': 'https://api.github.com/users/ludeeus/orgs', 'received_events_url': 'https://api.github.com/users/ludeeus/received_events', 'repos_url': 'https://api.github.com/users/ludeeus/repos', 'site_admin': False, 'starred_url': 'https://api.github.com/users/ludeeus/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ludeeus/subscriptions', 'type': 'User', 'url': 'https://api.github.com/users/ludeeus'}

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, {'avatar_url': 'https://avatars2.githubusercontent.com/u/15093472?v=4', 'events_url': 'https://api.github.com/users/ludeeus/events{/privacy}', 'followers_url': 'https://api.github.com/users/ludeeus/followers', 'following_url': 'https://api.github.com/users/ludeeus/following{/other_user}', 'gists_url': 'https://api.github.com/users/ludeeus/gists{/gist_id}', 'gravatar_id': '', 'html_url': 'https://github.com/ludeeus', 'id': 15093472, 'login': 'ludeeus', 'node_id': 'MDQ6VXNlcjE1MDkzNDcy', 'organizations_url': 'https://api.github.com/users/ludeeus/orgs', 'received_events_url': 'https://api.github.com/users/ludeeus/received_events', 'repos_url': 'https://api.github.com/users/ludeeus/repos', 'site_admin': False, 'starred_url': 'https://api.github.com/users/ludeeus/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ludeeus/subscriptions', 'type': 'User', 'url': 'https://api.github.com/users/ludeeus'}

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, {'avatar_url': 'https://avatars2.githubusercontent.com/u/15093472?v=4', 'events_url': 'https://api.github.com/users/ludeeus/events{/privacy}', 'followers_url': 'https://api.github.com/users/ludeeus/followers', 'following_url': 'https://api.github.com/users/ludeeus/following{/other_user}', 'gists_url': 'https://api.github.com/users/ludeeus/gists{/gist_id}', 'gravatar_id': '', 'html_url': 'https://github.com/ludeeus', 'id': 15093472, 'login': 'ludeeus', 'node_id': 'MDQ6VXNlcjE1MDkzNDcy', 'organizations_url': 'https://api.github.com/users/ludeeus/orgs', 'received_events_url': 'https://api.github.com/users/ludeeus/received_events', 'repos_url': 'https://api.github.com/users/ludeeus/repos', 'site_admin': False, 'starred_url': 'https://api.github.com/users/ludeeus/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ludeeus/subscriptions', 'type': 'User', 'url': 'https://api.github.com/users/ludeeus'}

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, {'avatar_url': 'https://avatars2.githubusercontent.com/u/15093472?v=4', 'events_url': 'https://api.github.com/users/ludeeus/events{/privacy}', 'followers_url': 'https://api.github.com/users/ludeeus/followers', 'following_url': 'https://api.github.com/users/ludeeus/following{/other_user}', 'gists_url': 'https://api.github.com/users/ludeeus/gists{/gist_id}', 'gravatar_id': '', 'html_url': 'https://github.com/ludeeus', 'id': 15093472, 'login': 'ludeeus', 'node_id': 'MDQ6VXNlcjE1MDkzNDcy', 'organizations_url': 'https://api.github.com/users/ludeeus/orgs', 'received_events_url': 'https://api.github.com/users/ludeeus/received_events', 'repos_url': 'https://api.github.com/users/ludeeus/repos', 'site_admin': False, 'starred_url': 'https://api.github.com/users/ludeeus/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ludeeus/subscriptions', 'type': 'User', 'url': 'https://api.github.com/users/ludeeus'}

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, {'avatar_url': 'https://avatars2.githubusercontent.com/u/15093472?v=4', 'events_url': 'https://api.github.com/users/ludeeus/events{/privacy}', 'followers_url': 'https://api.github.com/users/ludeeus/followers', 'following_url': 'https://api.github.com/users/ludeeus/following{/other_user}', 'gists_url': 'https://api.github.com/users/ludeeus/gists{/gist_id}', 'gravatar_id': '', 'html_url': 'https://github.com/ludeeus', 'id': 15093472, 'login': 'ludeeus', 'node_id': 'MDQ6VXNlcjE1MDkzNDcy', 'organizations_url': 'https://api.github.com/users/ludeeus/orgs', 'received_events_url': 'https://api.github.com/users/ludeeus/received_events', 'repos_url': 'https://api.github.com/users/ludeeus/repos', 'site_admin': False, 'starred_url': 'https://api.github.com/users/ludeeus/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ludeeus/subscriptions', 'type': 'User', 'url': 'https://api.github.com/users/ludeeus'}

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, {'avatar_url': 'https://avatars2.githubusercontent.com/u/15093472?v=4', 'events_url': 'https://api.github.com/users/ludeeus/events{/privacy}', 'followers_url': 'https://api.github.com/users/ludeeus/followers', 'following_url': 'https://api.github.com/users/ludeeus/following{/other_user}', 'gists_url': 'https://api.github.com/users/ludeeus/gists{/gist_id}', 'gravatar_id': '', 'html_url': 'https://github.com/ludeeus', 'id': 15093472, 'login': 'ludeeus', 'node_id': 'MDQ6VXNlcjE1MDkzNDcy', 'organizations_url': 'https://api.github.com/users/ludeeus/orgs', 'received_events_url': 'https://api.github.com/users/ludeeus/received_events', 'repos_url': 'https://api.github.com/users/ludeeus/repos', 'site_admin': False, 'starred_url': 'https://api.github.com/users/ludeeus/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ludeeus/subscriptions', 'type': 'User', 'url': 'https://api.github.com/users/ludeeus'}

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, {'avatar_url': 'https://avatars2.githubusercontent.com/u/15093472?v=4', 'events_url': 'https://api.github.com/users/ludeeus/events{/privacy}', 'followers_url': 'https://api.github.com/users/ludeeus/followers', 'following_url': 'https://api.github.com/users/ludeeus/following{/other_user}', 'gists_url': 'https://api.github.com/users/ludeeus/gists{/gist_id}', 'gravatar_id': '', 'html_url': 'https://github.com/ludeeus', 'id': 15093472, 'login': 'ludeeus', 'node_id': 'MDQ6VXNlcjE1MDkzNDcy', 'organizations_url': 'https://api.github.com/users/ludeeus/orgs', 'received_events_url': 'https://api.github.com/users/ludeeus/received_events', 'repos_url': 'https://api.github.com/users/ludeeus/repos', 'site_admin': False, 'starred_url': 'https://api.github.com/users/ludeeus/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ludeeus/subscriptions', 'type': 'User', 'url': 'https://api.github.com/users/ludeeus'}

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, {'avatar_url': 'https://avatars2.githubusercontent.com/u/15093472?v=4', 'events_url': 'https://api.github.com/users/ludeeus/events{/privacy}', 'followers_url': 'https://api.github.com/users/ludeeus/followers', 'following_url': 'https://api.github.com/users/ludeeus/following{/other_user}', 'gists_url': 'https://api.github.com/users/ludeeus/gists{/gist_id}', 'gravatar_id': '', 'html_url': 'https://github.com/ludeeus', 'id': 15093472, 'login': 'ludeeus', 'node_id': 'MDQ6VXNlcjE1MDkzNDcy', 'organizations_url': 'https://api.github.com/users/ludeeus/orgs', 'received_events_url': 'https://api.github.com/users/ludeeus/received_events', 'repos_url': 'https://api.github.com/users/ludeeus/repos', 'site_admin': False, 'starred_url': 'https://api.github.com/users/ludeeus/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ludeeus/subscriptions', 'type': 'User', 'url': 'https://api.github.com/users/ludeeus'}

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, {'avatar_url': 'https://avatars2.githubusercontent.com/u/15093472?v=4', 'events_url': 'https://api.github.com/users/ludeeus/events{/privacy}', 'followers_url': 'https://api.github.com/users/ludeeus/followers', 'following_url': 'https://api.github.com/users/ludeeus/following{/other_user}', 'gists_url': 'https://api.github.com/users/ludeeus/gists{/gist_id}', 'gravatar_id': '', 'html_url': 'https://github.com/ludeeus', 'id': 15093472, 'login': 'ludeeus', 'node_id': 'MDQ6VXNlcjE1MDkzNDcy', 'organizations_url': 'https://api.github.com/users/ludeeus/orgs', 'received_events_url': 'https://api.github.com/users/ludeeus/received_events', 'repos_url': 'https://api.github.com/users/ludeeus/repos', 'site_admin': False, 'starred_url': 'https://api.github.com/users/ludeeus/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ludeeus/subscriptions', 'type': 'User', 'url': 'https://api.github.com/users/ludeeus'}

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, {'avatar_url': 'https://avatars2.githubusercontent.com/u/15093472?v=4', 'events_url': 'https://api.github.com/users/ludeeus/events{/privacy}', 'followers_url': 'https://api.github.com/users/ludeeus/followers', 'following_url': 'https://api.github.com/users/ludeeus/following{/other_user}', 'gists_url': 'https://api.github.com/users/ludeeus/gists{/gist_id}', 'gravatar_id': '', 'html_url': 'https://github.com/ludeeus', 'id': 15093472, 'login': 'ludeeus', 'node_id': 'MDQ6VXNlcjE1MDkzNDcy', 'organizations_url': 'https://api.github.com/users/ludeeus/orgs', 'received_events_url': 'https://api.github.com/users/ludeeus/received_events', 'repos_url': 'https://api.github.com/users/ludeeus/repos', 'site_admin': False, 'starred_url': 'https://api.github.com/users/ludeeus/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ludeeus/subscriptions', 'type': 'User', 'url': 'https://api.github.com/users/ludeeus'}

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, {'avatar_url': 'https://avatars2.githubusercontent.com/u/15093472?v=4', 'events_url': 'https://api.github.com/users/ludeeus/events{/privacy}', 'followers_url': 'https://api.github.com/users/ludeeus/followers', 'following_url': 'https://api.github.com/users/ludeeus/following{/other_user}', 'gists_url': 'https://api.github.com/users/ludeeus/gists{/gist_id}', 'gravatar_id': '', 'html_url': 'https://github.com/ludeeus', 'id': 15093472, 'login': 'ludeeus', 'node_id': 'MDQ6VXNlcjE1MDkzNDcy', 'organizations_url': 'https://api.github.com/users/ludeeus/orgs', 'received_events_url': 'https://api.github.com/users/ludeeus/received_events', 'repos_url': 'https://api.github.com/users/ludeeus/repos', 'site_admin': False, 'starred_url': 'https://api.github.com/users/ludeeus/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ludeeus/subscriptions', 'type': 'User', 'url': 'https://api.github.com/users/ludeeus'}

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by iantrich** [comment]
testing the smarts

**Comment by ludeeus** [comment]
Hi, iantrich

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, ludeeus

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, ludeeus

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, ludeeus

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, ludeeus

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, ludeeus

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, ludeeus

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, ludeeus

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, ludeeus

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, ludeeus

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, ludeeus

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, ludeeus

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, ludeeus

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, ludeeus

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, ludeeus

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, ludeeus

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, ludeeus

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, ludeeus

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, ludeeus

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, ludeeus

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, ludeeus

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, ludeeus

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, ludeeus

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, ludeeus

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, ludeeus

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, ludeeus

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, ludeeus

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, ludeeus

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, ludeeus

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, ludeeus

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, ludeeus

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, ludeeus

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, ludeeus

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, ludeeus

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by iantrich** [comment]
testing ludeeus' bot skillz

**Comment by ludeeus** [comment]
Hi, iantrich

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
That was a 💩 fest, sorry about that @eifinger :D

**Comment by eifinger** [comment]
I actually had a pretty good laugh :D

**Comment by ludeeus** [comment]
Hi, @eifinger

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Comment by ludeeus** [comment]
Hi, @eifinger

This issue is closed, closed issues are ignored.
If you have issues similar to this, please open a seperate issue.

https://github.com/custom-components/hacs/issues/new/choose

And remember to fill out the entire issue template :)



_This message was automatically generated🚀_

**Pull request closed without merging**
