### PR TITLE
Adding Meross IoT library

### PR DESCRIPTION
**Pull request by albertogeniola**
Proposing the Meross HomeAssistant Custom component as default one.

### CODE REVIEW

**Comment by ludeeus** [comment]
@albertogeniola This has started to fail.
You now only have one release on GH, that is a pre-release, and the structure in that is not compliant for HACS use.

I'm releasing 0.10.0 later today and will have to remove this if it's not working.

**Comment by albertogeniola** [comment]
Hi,
Thank you for pointing it out. Just corrected the CI/CD pipeline that caused the mistake. Could you please confirm it's now ok with the next release?

**Comment by ludeeus** [comment]
image
Looks good now :+1:

**Comment by albertogeniola** [comment]
Great, awesome support. Keep it up!

**Pull request merged**
