### PR TITLE
Update install.md

### PR DESCRIPTION
**Pull request by apop880**
Clarify that logger needs to be in config, and Home Assistant needs to be restarted, before you can add HACS to the config file.

### CODE REVIEW

**Comment by ludeeus** [comment]
This does not sound correct, ha does not remember components you had during last startup

**Comment by ludeeus** [comment]
Did a test now, removed both `logger` and `hacs` from my config, then did a restart, then added both back and a new restart, everything works as it should.

**Comment by apop880** [comment]
When I set up HACS earlier tonight, the config checker kept giving me `component not found: hacs`. I had to add logger to configuration.yaml because it wasn't there already. But I couldn't add logger and hacs at the same time and pass the config check. So I had to add logger, restart add HACS, and then I could pass the check and restart again.

Maybe I could have forced HASS to restart anyways and it would have been fine, but it is more intuitive if it passes the config check through the whole setup sequence.

**Comment by ludeeus** [comment]
Sounds like a bug in the config check, it should evaluate the new config, and that is valid...
A force would have worked, that's what I do :)

**Pull request merged**
