### PR TITLE
Docs update Terminal Install instructions.

### PR DESCRIPTION
**Pull request by DeadEnded**
Add directions for terminal download to step 3.

### CODE REVIEW

**Comment by DeadEnded** [comment]
My first commit was already merged... not sure how to remove it from this pull request.

Thanks,
DeadEnd

**Comment by ludeeus** [comment]
This is a bad idea, this will fetch the master branch, that one is at times not runnable since I push every commit there.

If you rework it to checkout the latest tag (if that is even possible) I'll accept it :)

**Comment by DeadEnded** [comment]
Okay, thanks... I'll close this and try again.

**Comment by DeadEnded** [comment]
@ludeeus 
Okay - I am fighting trying to figure this out.
I am trying to create the pull request, and it shows the change I am making - but it shows 4 commits now - even though only 1 of them is the change I am trying to make.  I am new to Github - and this is my first adventure into contributing.

Should I care about the commits it lists, or just the file changes it shows?
If I have commits that are already merged into the master - how can I make them not appear in the pull request?  Sorry if these are odd questions - still learning!

Lastly - your comment about about tag instead of master... do you mean you would prefer me to do the pull request against the tag instead of master branch??  I ask because I checked most of the other pull requests and they go to Master.  Again, not sure of "best practice".

Thanks for the help!
DeadEnd

**Comment by DeadEnded** [comment]
I found a good write up on forks and branches for development:
[GitHub Standard Fork & Pull Request Workflow](https://gist.github.com/Chaser324/ce0505fbed06b947d962)

Going forward I will use this as a reference - should help greatly in making sense of how to do things.

Cheers!
DeadEnd

**Comment by ludeeus** [comment]
> If I have commits that are already merged into the master - how can I make them not appear in the pull request?

That would be rebasing :)

I usually follow this guide for that :)
https://developers.home-assistant.io/docs/en/development_catching_up.html

**Pull request closed without merging**
